# Makefile of MyProtocol

include $(PROJ_ROOT)/IncludePre.mk

LIB_NAME = MyProtocol
LIB_SRCS = MyProtocol.c 
TARGET_SRCS = MyClient.c TestConnection.c TestDataChange.c TestDrinking.c

LIBS += -lMyNetwork -lMyThread

include $(PROJ_ROOT)/IncludePost.mk
