# Makefile of MyThread

include $(PROJ_ROOT)/IncludePre.mk

LIB_NAME = MyThread
LIB_SRCS = MyMutex.c MySemaphore.c MyThread.c
TARGET_SRCS = TestMutex.c TestSemaphore.c TestThread.c 

include $(PROJ_ROOT)/IncludePost.mk
